// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "amplifyreactapp-20190117001725-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d3ucpzz0n23r11.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-west-2:eae6472a-35c2-4e3e-89f2-78af8ac5f318",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_7zacEN0nf",
    "aws_user_pools_web_client_id": "1ekmdjuu41ni3tn2afpgi8n6lm"
};


export default awsmobile;
